### ISSUE TITLE
New feature requested: "skip" story button

### ISSUE THREAD

**Issue by kayosu** [29988122/Fate-Grand-Order_Lua#102]
kind of want to skip the story

**Comment by potchy** [comment]
I can do this, but I'll need screenshots of the skip button from every server (CN, TW, JP).
I already got one for NA.

![screenshot_2018-11-27-21-00-16](https://user-images.githubusercontent.com/4316326/49117354-8921ca80-f287-11e8-9765-97f76f349aca.png)

**Comment by kayosu** [comment]
![46872013_277015142862490_6070850248996028416_n](https://user-images.githubusercontent.com/45334770/49156961-3876a400-f351-11e8-887e-71911ee76e63.png)
here is JP's
thank for your work btw

**Comment by aqer** [comment]
![screenshot_2018-11-28-23-06-53](https://user-images.githubusercontent.com/24737421/49160844-9f508900-f362-11e8-9948-28e981ecc96d.png)
TW is here :)

**Comment by 29988122** [comment]
@aqer 
哇所長耶，好懷念喔

萌擔當薄倖擔當被胖子取代了（淚

**Comment by aqer** [comment]
@29988122 
希望有機會再出場啊

等待，並懷抱希望吧

**Comment by Keichide** [comment]
Is it really a good idea to go in this Direction and even let the Script, skip the Story for someone? I mean i only ever wanted something like an Autbot for fate because i'm tired of farming the same quest over and over again (which is a pain in the ass anyway since Aniplex should know, that the western audiense hates Farming.) But i never intended to just put it on a story quest und let it play for me, while i do something else. I believe the whole script should focus soley on this scenario where you have to farm like crazy a boring 4-5 turn quest (Embers, QP, Event Items) and not on playing the whole game autonomus for someone.

**Comment by potchy** [comment]
@kayosu I didn't forget this, we're just busy with other stuff

@Keichide the script won't be able to win difficult fights like Gawain's by itself anyway, so I don't see why not

**Comment by l3ombyx** [comment]
@Keichide A little late of a response but it's good to keep in mind sometimes people like having side accounts, or starting over after rolling for servants they want more. Have a skip button is nice because it lets you get back to where you were with out the issue of having to slog through the first few singularities you've probably been through a dozen times. 

In any case I can't wait to see this implemented but of course no rush!

**Comment by iqbalefef** [comment]
How to skip story ? Is it already automatically right now ? Because mine is not skipping automatically

**Comment by Gorgatron** [comment]
Is this still planned?

**Comment by 29988122** [comment]
Should be done, tested.

Try the latest commit, and make
```
StorySkip == 1
```
in your config file.
