### ISSUE TITLE
(ways to capture screen) Is "Screenshot by... Media Protection" in AnkuLua really better?

### ISSUE THREAD

**Issue by Keichide** [29988122/Fate-Grand-Order_Lua#125]
I just played a bit around with the Settings in Ankulua, since i had "Screenshot by" and "Click" set on "Deamon" before, which had some serious Performance Issues on the Script, like.. "Can not derterminate Card Typ" slow scrolling in the Support List or clicking on the wrong Area, not confirming skill usage etc... 

So i just selected the Media Protection for taking the Screenshots in AnkuLua and it's really a HUGE Speedup, without any bad behaviors on the Script.. So is it just me, or was it commen sense and i just did'nt know it?

**Comment by Keichide** [comment]
Like i said... I get most of the Error Messages just if i let the Deamon in AnkuLua capture the Screenshot but not if i take the Media Protection function. For now it only happens more frequently that i get a "Runtime error: java.IOExeption: Media Protection screenshot fail" Message

**Comment by potchy** [comment]
Okay, so I tested this Media Projection method and it performs really terrible in my phone.
FGO plays at 10FPS max with it turned on. lol

**Comment by TryBane** [comment]
I've tested this as well, and also turned on the fastclick beta option while testing the changes I've made to the script. I've seen a massive speedboost on the device, and even if the fps drops, the things done are still active (so even if the screen doesn't show a card selected it'll still be selected by the program)

I don't know if that is just the case with my phone though. But the speed boost from Fastclick is also massive. Something we may want to include in the readme, though it should be noted that not all devices will support it.

**Comment by TryBane** [comment]
After further testing I feel the speed boost on my device is due to fastclick more than anything else. And media projection might have only been implemented after ankulua 8.0.0, which in their changelog states it supports android 8.0 without needing USB debugging!

Important to note that there is a bit of runaround to get it working on android 8.0 without daemon, which will require the media projection itself to make it work.

Might want to get someone to test this themselves and update the readme to reflect the steps to take on an android 8.0 or higher device.

**Comment by potchy** [comment]
I'll mark this as an enhancement, even though it's related to documentation.
