### ISSUE TITLE
Please add RESIST card detection in norcard function

### ISSUE THREAD

**Issue by nekomania** [29988122/Fate-Grand-Order_Lua#14]
It would be ideal if the script will try to avoid choosing RESIST card during battle.
WEAK > nil card > RESIST

Thank you.

**Comment by 29988122** [comment]
Umm.... 
I'd need two other versions of screenshot from EN fgo and TW fgo, in order to achieve this.

I personally only have JP version account, and add this function in JP version *only* will cause some inconsistency in code, which I'd like to prevent.

If someone can screenshot them, then I'd love to do so.

**Comment by ryuga93** [comment]
Hey sorry for joining in late, but I just did some searching for the resist card images and it turns out that all 3 servers use the same blue word. So I think using just the JP version should be ok.

**Comment by 29988122** [comment]
Try 1.4.5 release and see the results.
I did a brief test, and it should be OK.

P.S. still need someone to screenshot a CN version of FGO, or maybe KR version too..

**Comment by ryuga93** [comment]
FML, finally got it to run on ME*Ahem*mu...

Will test it later, I need to sleep...

Well, at least now I can try to work on the [Better chaining / card order selection](https://github.com/29988122/Fate-Grand-Order_Lua/issues/10) logic easier.

**Comment by 29988122** [comment]
Just curious, do you have a plan about it?

Like..umm, will it be weight based (card score? therefore a brave chain from the same servant could have a higher weight than three weak cards, and maaaaybe red cards have a higher weight than blue and green..), or it will be more simpler than above and have fewer rules with regards to different servants?(real time capture & recognition could be hard to implement by ankulua IIRC)

Because I have no idea how I played this game, really. I was using stones to continue all the time. lol.
I have like.. 4 kaleido scope, which make ult spamming possible.

**Comment by ryuga93** [comment]
Yup, based on card score, but I don't think servant brave chain is feasible, that will just make it slower.

Real time capture & recognition can be done using pixel color picking method, by just detecting colors in several locations instead of a whole picture(for example detecting the white pixel of running Fou and another black pixel in loading screen, this will make the script waiting flexible instead of a sleep(10)).

Another thing is skill, probably autoskill can be done with predefined setting:
1) Define all 9 skill locations into 9 alphabets(a,b,c | i,j,k | x,y,z)
2) Define the servant selection into 1,2,3
3)Define a string for skill input based on turn number using delimiter as turn determination, eg:
(||ax|b2||i2j|) means
turn 1: no skill
turn 2: servant 1 skill 1 & servant 3 skill 1
turn 3: servant 1 skill 2 buff servant 2
turn 4: no skill
turn 5: servant 2 skills 1 buff itself then skill 2

Beyond this we would be looking at AI and Machine Learning, which probably IMO is a bit overkill lol

**Comment by 29988122** [comment]
Sounds cool, glad that someone else can join this project : p
Ya that would definitely makes 周回 of harder stages possible during events.

Still, I have no idea how to write the code tho, might as will learn from yours.
If you checked the resist code, you can understand that it's quite ...messy? Due to the fact that I don't know how to make it simple & elegant & easy to maintain..guess I still have a long way to go.

Anyway, happy new year!
