### ISSUE TITLE
Runtime Error 

### ISSUE THREAD

**Issue by Deidaratono** [29988122/Fate-Grand-Order_Lua#150]
Hello there,

I'm currently trying to get it working.
I've seem to sucessfully install the run.bat , at least it states that it is successful.
![grafik](https://user-images.githubusercontent.com/7028113/50538831-8b24c500-0b76-11e9-8b60-04226728eeb7.png)
only thing that seems to be out of place is "unable to connect to 127.0.0.1:6555:6555"

The AnkuLua app states no error when starting or selecting the script.
Then I start the game, press start for the script and receive the empty message box (which seems to be normal according to other posts?)
after some time I'm receiving the following error:
![screenshot_20181229-140032](https://user-images.githubusercontent.com/7028113/50538847-e3f45d80-0b76-11e9-892e-c23581bd0255.jpg)
![screenshot_20181229-140045](https://user-images.githubusercontent.com/7028113/50538849-e8207b00-0b76-11e9-8faf-4f890c4f3a0d.jpg)
here it also states the issue with "unable to connect to 127.0.0.1" ?
I've already tried to reboot my phone and install the deamon again (same window)

System:
device: Huawei P20 Pro
android: Android 8.1
AnkuLua: 8.1.1-trial

According to older posts it states that Android 8.0 an higher is not supported, but I can't find this information in the current readme-file, so I suppose it's working now?

**Comment by vit2657** [comment]
I had a same problem and googling told me that daemon gets killed on android 8+ when you turn off usb debug. Latest version of Ankulua however does not require daemon for android 8+, just have to switch settings in there to Media Projection screenshots and touches by Accessibility. This at least works fine for me.

**Comment by Deidaratono** [comment]
Now I'm getting the following error:
![screenshot_20181229-171220](https://user-images.githubusercontent.com/7028113/50540187-67b94480-0b8d-11e9-86d4-f6fa87836428.jpg)

**Comment by TryBane** [comment]
Which version of Ankulua are you using?

**Comment by TryBane** [comment]
Okay, so found a thread that seemed to be related to the issue you posted. The issue it seemed to be was the ads that are shown? The entire conversation is in Chinese and was pre-Ankulua 8.0 it seems, but it was the same error regarding Media Projection issue, on the same game TW server, and he said that the error didn't occur when there wasn't an ad. Also, he said there didn't seem to be a way to remove the ad. I think he rebooted the phone (or rebooted Ankulua) and it wasn't there eventually.

Give it a shot, and see if it solves the issue. Hopefully, since I personally have not run into this issue. Also as a side-note, running the free version of Ankulua might have ads, but the real issue is that there is a time-limit. I personally suggest investing in the app as I feel it is worth it to run for long periods of time and it isn't the most expensive thing in the world that I've seen. $50 for life is pretty good, especially when it can be used for MORE than just this game.

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/README.md#android-81-and-above

Refer to this section for more detail.

You can still reopen the ticket if you encountered any issue!
