### ISSUE TITLE
Fate-Grand-Order_JS

### ISSUE THREAD

**Issue by fauricio9656** [29988122/Fate-Grand-Order_Lua#152]
202/5000
good sorry for bother but they can do the lua script to js is for robotmon I'm new in this programming nose how to do it for a bot that I found but does not run files lua sorry for the inconvenience caused

**Comment by potchy** [comment]
I'm really sorry, but I don't understand what you're trying to say. @_@

**Comment by fauricio9656** [comment]
> 
> 
> I'm really sorry, but I don't understand what you're trying to say. @_@

was that if someone helped to make a script in robotmon for farm like the Japanese and Chinese do https://sites.google.com/view/fgoautoscript?fbclid=IwAR2MEF_bi9HkaJg5nVJy4QTJaztWBr75CYht1oCf4V9kf9uI1aRzCT8RTZw

**Comment by fauricio9656** [comment]
> 
> 
> @29988122
> wow a competitor XD
> 
> @potchy
> https://sites.google.com/view/fgoautoscript/%E6%93%B7%E5%8F%96%E5%A5%BD%E5%8F%8B%E5%BE%9E%E8%80%85%E7%A6%AE%E8%A3%9D?authuser=0
> 
> This crop support servant/CE feature not bad (if you need "human" translation let me know)

I would do it for na but nose for programming so I came to ask for help here t---t

**Comment by ryuga93** [comment]
I doubt we will move to JS, and @29988122 knew about it few months ago (sorry wasn't aware of it). It will be a duplication of effort for both us and that JS script owner. But still it's up to @29988122 to decide.

So as a contributor all I can suggest is to use Ankulua to run our script, or make a request to the JS script owner to support EN server.

**Comment by 29988122** [comment]
I think the competition between Robomon and Ankulua is somewhat healthy XD 
Cheaper and better product is always welcome in the b2c field.

***

Besides that, I tend to make things "as-is" - we maintain ours in Lua, they maintain theirs in js. (As discussed before with you guys, this is a small project, so XD)

And the EN server support..Since this repo's MIT license, I don't mind if they use our cropped images..XD
Maybe @fauricio9656 can ask them for help I guess?

**Comment by potchy** [comment]
Why do you want us to port it to Robotmon though? I mean, how is it better? I wouldn't do it just because.

**Comment by fauricio9656** [comment]
> 
> 
> I doubt we will move to JS, and @29988122 knew about it few months ago (sorry wasn't aware of it). It will be a duplication of effort for both us and that JS script owner. But still it's up to @29988122 to decide.
> 
> So as a contributor all I can suggest is to use Ankulua to run our script, or make a request to the JS script owner to support EN server.

ok I understand sorry for the inconvenience

**Comment by fauricio9656** [comment]
> 
> 
> I think the competition between Robomon and Ankulua is somewhat healthy XD
> Cheaper and better product is always welcome in the b2c field.
> 
> Besides that, I tend to make things "as-is" - we maintain ours in Lua, they maintain theirs in js. (As discussed before with you guys, this is a small project, so XD)
> 
> And the EN server support..Since this repo's MIT license, I don't mind if they use our cropped images..XD
> Maybe @fauricio9656 can ask them for help I guess?
I said it because some of us can not pay the license for any reason and sometimes I would like to farm all night because in the day I can not do programming to do all the robotmon said they will not do it for na (sure they hate us for the massive troll the pillars of solomon) if someone helps me in this miniproject I would be grateful because it would help  ; _;

**Comment by fauricio9656** [comment]
> Why do you want us to port it to Robotmon though? I mean, how is it better than AnkuLua? I'm talking about features, not price. I wouldn't do it just because.

of course it is better AnkuLua but the bad is the trial version of farmear 30 mints some have the slow internet that in 30 minutes farmean 1 map I do not complain about the price if I had the money I would pay the pro version but I come to ask for help because it is easier for some leave all night farmeando I try to get up every 30 mints at night to wait to activate again while in robotmon one can leave normally all night but all robotmon is for Japanese and Chinese server hopefully not bother my message for my post to ask for help t---t  I just want to make everything easier for those of us who have to get up at dawn to farm bound or ce and have to study or get up early and do not have time for anything

**Comment by ryuga93** [comment]
I suggest you to instead of trying to get up every 30 min at night to rerun the script, you are better off spending 3 sleepless night to learn JS and how to code in Robotman, or get a freelance or something to have the money. 

There is no such thing as "cannot" in learning, you are either lazy or the end goal not important for you. Even @29988122 managed to wrote the initial script before I came, and he did it without prior experience in coding in uni (correct me if I'm wrong).

And some facts about me. My "formal" education on coding was until pointers in C++, and at that time I did not even managed understand what that "monster" is. What I know about coding today was countless nights of minimum sleep!

Sorry if I sounded harsh, but it just triggers me when someone say he/she can't learn/do something, due to time/money/age/whatever. I have no knowledge of how your life is currently, but I'm sure everyone here does not have an easy life.

If you want something, you'll have to pay a price.

**Comment by fauricio9656** [comment]
> 
> 
> Robotman's API seems to be fairly solid and the UI looks nice, but it would be too troublesome to port everything we already have to it. You can probably get that one running by replacing all images with ones from the EN server. Here's the project's repository: https://github.com/r2-studio/robotmon-scripts/tree/master/scripts/com.cooper.FGO
> 
> But honestly, it's just easier to drop US$3.5 for AnkuLua's monthly license. When there aren't any events going on or you have the time to farm manually, just don't buy another license until you need it again. I'm cheap, so I do that pretty often. 😄
> 
> > sure they hate us for the massive troll the pillars of solomon
> 
> LOL

hello sorry for disturbing change the images but I have an error comes in and do not choose the friends then it stays so do not choose anything @potchy would help me pick it up if you can t--t 
[image_jp.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2729937/image_jp.zip)

**Comment by potchy** [comment]
Unfortunately, I can't devote my time to make that script work, so the rest is up to you.
