### ISSUE TITLE
i can't create my own servantsCE image

### ISSUE THREAD

**Issue by Volskis** [29988122/Fate-Grand-Order_Lua#178]
i do the exect same steps and the script can't identify the image

**Comment by Volskis** [comment]
i dont know what i am doing wrong maybe is the 720x pixels?

**Comment by TryBane** [comment]
Can you post a picture with the image you're trying to make into the Support?

There are a few things that you need to make sure of. The Screenshot you initially take should be of the entire game screen. Second, you resize the image FIRST, setting it to either 720 height or 1280 width keeping the aspect ratio. If you don't have bars on the top/bottom of the screen or don't have bars on the left/right side of the screen, then this should work fine.

If you DO have bars, then you'll need to set it to 720 height if you have bars on the left/right or 1280 width if you have bars on the top/bottom. Keep the aspect ratio in both cases otherwise it won't work.

After that is finished, you can then crop the image as necessary. There is no further need to resize the image at this point.

**Comment by Volskis** [comment]
it's okay now, ty for the reply at least i got more info now
