### ISSUE TITLE
AnkuLua_Pro only works for about 3 clicks

### ISSUE THREAD

**Issue by Gorgatron** [29988122/Fate-Grand-Order_Lua#181]
The script stops after basically doing 3 battle actions in a fight at the most. I am on the NA server, using nox player, and I have tested with AnkuLua_Pro2v8.3.0-pro2 and AnkuLuaTrial.v8.3.0. The trial version will go on until the cooldown appears for the trial but with the pro it stops after 3 turns basically.

Here is a screenshot I noticed on trial and pro so im not sure if it helps: [https://i.imgur.com/jwfSLNJ.png](url)

**Comment by TryBane** [comment]
This is an odd one. I am assuming you are using Autoskill. Could you post the Autoskill command list string you are using?

**Comment by Gorgatron** [comment]
@TryBane Thank you for responding. I am a new player (level 34) and I'm trying to blast through the main quest line to do end game content with friends.

This is what I have set in my auto skill list. I have Ibaraki and Heracles in my main party who only have 1 skill.

`--AutoSkill
Enable_Autoskill = 1
Skill_Confirmation = 0
--Skill_Command = "abc,#,def,#,ghi"
Skill_Command = "k2l1adfghi2,0,#,0,j1,#,0,j2,#,456"

--AutoSkillList
Enable_Autoskill_List = 1

Autoskill_List[1][1] = "Settings No.1"
Autoskill_List[1][2] = "k2l1adfghi2,0,#,0,j1,#,0,j2,#,456"

Autoskill_List[2][1] = "Settings No.2"
Autoskill_List[2][2] = "abc,#,def,#,ghi"`

**Comment by TryBane** [comment]
Based on what you said here, the given command list would attempt to use the 3rd skill of Herc despite it not being there. That in itself isn't an issue since it won't cause any problems. But thought I should mention it to prevent it being a problem in your future.

Now what I'm curious about is why the master skills are not activating. The beginning of your command list use the 2nd and 3rd master skills, so that seems a bit weird. Also, if you need a command list that doesn't use skills you can just delete the commands in the second one and leave it blank.

As for your issue with Support selection, could you provide some information on the problem/s occurring? Such as if it is selecting the wrong servant, not selecting the right CE, or if it isn't scrolling or if it pops up with a problem?

**Comment by Gorgatron** [comment]
The master skills do work but the main issue I am noticing is that I have the pro version of ankulua that stops doing anything after about three turns but the trial version will keep going until the timer cooldown. I am currently using the trial version and micro managing it to skip cut scenes to progress further when I thought the pro version would not stop (minus skipping cut scenes) but it stops doing anything after the third turn.

When it comes to support I made crops of just the friend's support picture only and the full region with login details to the far right. Here are the two samples:

[https://i.imgur.com/vkrJGDx.png](https://i.imgur.com/vkrJGDx.png) and [https://i.imgur.com/OBnfpQs.png](https://i.imgur.com/OBnfpQs.png)

Here is my current sample which is commented out since the script scrolls repeatedly but cannot make any selection.

`--AutoSupportSelection
Support_SelectionMode = "preferred"
Support_SwipesPerUpdate = 10
Support_MaxUpdates = 3
Support_FallbackTo = "second"
Support_FriendsOnly = 1
Support_PreferredServants = "Koga_support.png, JC_support.png"
Support_PreferredCEs = "*chaldea_lunchtime.png"`

**Comment by Gorgatron** [comment]
Here is the error I got from the support problem: [https://i.imgur.com/x8YVZwT.jpg](https://i.imgur.com/x8YVZwT.jpg)

I tried checking the lines specified in the files but I know very little about programming and I did not see a conflict.

**Comment by TryBane** [comment]
Alright, I think I know the issue with the support. You have "second" there even though that isn't a supported command. Only first, preferred, and manual are valid. So that should fix the support issue specifically.

Still wondering what could be wrong with the command list... you don't have any capital letters correct? That may not affect the commands in itself but I would have to double check.

**Comment by TryBane** [comment]
Also, I take back what I said previously about the skill selections that you haven't unlocked for Herc and Ibaraki not affecting anything. It most certainly will. Delete all skill usage attempts on skills which you haven't unlocked and make sure that you aren't double clicking any skills. An instance where you click a skill that is still on cooldown will cause an issue of that skill menu coming up keeping you from progressing. I believe doing these two things will solve your skill command issues.

Also double checked the code for the error you posted regarding the support selection and your use or "second" is indeed the reason for that error. You have to use first, manual, or preferred. Specifically I am referring to your use of it in the fallback option.

Once you do these two things, and have tested them enough, come back and let me know if there is or isn't anymore issues with it. @Gorgatron

**Comment by Gorgatron** [comment]
@TryBane TY for pointing this out I forgot. I misunderstood the fallback option and resolved it by setting it to first to continue to automate it. The script tries to select the friend option I chose but it taps on the friend but keeps swiping. should Support_FriendsOnly remain at 1 for the value?

**Comment by TryBane** [comment]
If you specifically need friend supports, like so you can collect more FP or so you can actually use their NP, then yes, keep that as 1.
