### ISSUE TITLE
Hybrid Preferred/Manual OR Getting stuck on picking the last Mission

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#195]
Occasionally the Auto Grinding will get stuck on repeating the last mission, this most often occurs when it is the first time I am doing the mission likely because of the new Previous on the banner.

But it also happens on other occasions. 

If I turn it off and on again the problem resolves itself, this is more than fine the vast majority of days, but during Half Offs/Lotteries/Appling it becomes a problem as I leave for 25 minutes come back and find it only did one mission.

If it could automatically turn off after each mission, I could set up another Macro to turn it back on afterwards.  Manual/First isn't an option as it's getting stuck picking the mission, not the Support List which is never a problem.

I'd vastly prefer to keep preferred as well as having it always picking MLB Support CE's is extremely useful.

Where in the code would I look to change to make it auto turn off after each mission?

**Comment by 29988122** [comment]
I myself using first would also stuck due to slow emulator/slow android. (We use flat fixed wait() for now)

Unfortunately we don't have a proper logging function for now, so anything wait() too short could be THE problem.

3 main loops: https://github.com/29988122/Fate-Grand-Order_Lua/blob/eee2f96ad4c58c42446f189f66b1f7c9e61e17c8/regular.lua#L222

It could be in https://github.com/29988122/Fate-Grand-Order_Lua/blob/eee2f96ad4c58c42446f189f66b1f7c9e61e17c8/regular.lua#L76

or in https://github.com/29988122/Fate-Grand-Order_Lua/blob/eee2f96ad4c58c42446f189f66b1f7c9e61e17c8/regular.lua#L101

or in https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/modules/battle.lua

***

For the time being, I can only recommend you to try to increase some of the wait() in those codes.
Ankulua itself cannot be trigger restart within the code.

**Comment by Rajvir8** [comment]
Sorry for the delay I didn't notice the notification, I'll try modifying the numbers and see what fixes it.

**Comment by Rajvir8** [comment]
I tried 82 to see if that would change anything by changing it from 1.5 to 100 but there wasn't any change unfortunately.

**Comment by TryBane** [comment]
@Rajvir8 There has been a change that should have fixed this issue for you now! Please post here whether or not it is still causing you issues!

For reference, the change is that we added Support menu as a validator/actor, thus if it is in the Support menu, it will follow the script as appropriate for the Support menu, rather than wait a set amount of time before trying to do it.

**Comment by Rajvir8** [comment]
Thanks for your hard work guys, I've updated to the newest version and will try it out, I can't be sure if it immediately fixed the problem as it only occurred sometimes.  But if it goes a week or so without the issue popping up again I'll make sure to mention that it's fully fixed.

**Comment by TryBane** [comment]
@Rajvir8 There was an issue with the latest version regarding Support selection where it would crash. I just implemented a fix that I hope solves the issue, so please try the most recent one.

**Comment by Rajvir8** [comment]
@TryBane I noticed that it failed the moment I put it in Preferred mode and swapped back to my Older Version while trying to figure out the issue.

Glad to hear you fixed the crashing issue and I've reupdated to the newest version and tried it out, the preferred mode is currently working again and everything seems like it's working fine in the newest version at the moment.
