### ISSUE TITLE
Racing event farming script

### ISSUE THREAD

**Issue by Hikaru9569** [29988122/Fate-Grand-Order_Lua#201]
Was wondering if there was a script for the summer racing event? Works been insane and i dont have much time but really wanna clear the event
Edit; I should specify for NA

**Comment by 29988122** [comment]
Yes, and no.

You can check files in this folder:
https://github.com/29988122/Fate-Grand-Order_Lua/tree/master/_JP_past_events/JP_2018_07_summer_racing

Which I made a year ago.

However, our script has been heavily refactored by other contributors since then, so even I myself have no idea how to apply it to racing event currently...

***

Still, you can execute the old version of the script (config  	FGO_JP_EVENT_2018_07_summer_racing.lua, then it will execute summer_racing.lua in the same folder)

You can see if this works.

**Comment by DekaRose** [comment]
http://imgur.com/a/KEcRAMO

Yeah it seems to not work on my end, keep getting errors.

**Comment by potchy** [comment]
Why is it that you need a specific script for this event?
I haven't tried it yet. @_@

**Comment by DekaRose** [comment]
I just want to farm the currencies for the shop while I'm at work.

Ya know? kind of like the embers

**Comment by MrTroika** [comment]
Generic script should work ok if you set it up to use specific skills/NPs a turn.

**Comment by forgehe** [comment]
The generic script works for Part 1. 
Just make sure to change isEvent = 1 so it can click the extra dialogue box about using the boosts

**Comment by potchy** [comment]
see #170
it will come in handy
