### ISSUE TITLE
Plans to update the JP script due to new function?

### ISSUE THREAD

**Issue by w-san** [29988122/Fate-Grand-Order_Lua#202]
Any plans to update the script to accommodate the new function?

Since it sort of messes it up now.

**Comment by muvluvalt** [comment]
For the contributors who don't know what he's saying, it's likely this function here:

![image](https://user-images.githubusercontent.com/40586164/62424967-67c38900-b708-11e9-883f-dabcad743066.png)

**Comment by w-san** [comment]
Thank you good sir for explaining what i meant. :)

**Comment by potchy** [comment]
what the heck is this

**Comment by 29988122** [comment]
@potchy I'd like to thank myself for documenting this page in the past...
https://github.com/29988122/Fate-Grand-Order_Lua/wiki/In-Game-Result-Screen-Flow

It (the abovementioned picture)  appears right after 
```
Send Friend Request or not dialogue | two buttons to choose | 
```
There's no delay or loading between the two.

That is, if no code is modified, people in JP server cannot farm daily QP gate.

***

I'm unable to modify your code - I think it's better leaving that to you. <-bad coding habits.

**Comment by TheIanator** [comment]
It's a button to repeat the just finished quest. Left button cancels and drops you back where it normally would, right button drops you back in the support select.

Short term could just hit the left button and use the existing code, but long term it would save some loading time to code in hitting the right button.

**Comment by potchy** [comment]
Well, I don't have access to the JP server, so I'll be leaving this to you. 🙅‍♂

**Comment by w-san** [comment]
So is there a way to set it up so it press the left cancel button?

**Comment by TryBane** [comment]
I will apply a fix and have a friend or two test it.

**Comment by w-san** [comment]
Thank you very much and sorry for being a pain, (wish i know how to do stuff like this.)

**Comment by TryBane** [comment]
@w-san Give this a try. I'm at work so this was done between taking care of customers using my phone. So there is a good chance there are some issues. Just let me know if any crashes occur and the like. I only changed regular.lua and added a file to image_JP folder.

And if this works, be grateful! Was a pain to type it up between customers on mobile XD

**Comment by w-san** [comment]
@TryBane 

Wow i'll give this a test when i can.

I didnt expect you to work on this during your work time.

Dont know what to say other than thank you very much.

**Comment by TryBane** [comment]
It isn't an issue. It is just a pain to type when my concentration is split.

However, I expect there to be bugs. So just reply with any issues that do occur.

**Comment by w-san** [comment]
Okay i tried it out and it give me this error.

http://imgur.com/a/dSMqUyW

Once it goes pass the rewards screen it keeps tapping the next button and doesnt stop.

**Comment by TryBane** [comment]
Okay, I fixed the error that occurs. It was me using a previous variable name instead of the new one. The clicking should continue for 45 clicks then check for the menu that asks to continue. Go ahead of replace the regular.lua with the new one I just fixed.

**Comment by w-san** [comment]
@TryBane 

it works perfectly fine!

Thank you for your time and great work.

**Comment by TryBane** [comment]
Awesome! This is temporary for now. There are still some cases when it won't work like if you get a Bond CE. It also might have issues during specific Events if they ever implement it for Event Free Quests where you can get a CE drop. I can make that change later and submit a pull request at that time.

**Comment by w-san** [comment]
that's fair but for now it works for dailies so thank you so much for your hard work!

**Comment by TryBane** [comment]
Yep, no problem. When I get home in like 9 hours I'll fix that particular issue and maybe add some options. I realized that some people might actually want the farming to stop after they get a Bond CE, so I will add an option you can toggle to stop after Bond CE is attained. And of course fix the flow so that it will still work if you get one.

**Comment by w-san** [comment]
okay i'll just keep this open for now and i'll close the issue once it set up?
i got a servant close to bond CE so i can also test that out.

**Comment by TryBane** [comment]
Yeah, that way people can see there was indeed a resolution that just hasn't been merged yet.

**Comment by muvluvalt** [comment]
The new script does work but now the skills don't activate when the "continue" button is clicked.

So basically, skills work fine in my first run. After the "continue" button is clicked, it proceeds to the friend support screen, selects a support and proceeds to the second run.

Now, during this second run, skills won't activate. 

I made sure to download confirm.png and regular.lua from here: https://github.com/TryBane/Fate-Grand-Order_Lua

**Comment by TryBane** [comment]
Ah, I know why. Give me a minute to fix it.

**Comment by TryBane** [comment]
Done, redownload regular.lua and see if it works now.

**Comment by muvluvalt** [comment]
Yes it works now. Thank you very much!

**Comment by TryBane** [comment]
Yep! I expect it to still have a hiccup or two within the code so be sure to report any other issues that may arise. If that fixes it completely though then all the better!

**Comment by Kasdu** [comment]
After the first fight when the script enters the second fight it clicks on the servant on the right, which brings up the buffs and debuffs screen, and it stays there stuck. 
![Nox_2019-08-04_23-55-41](https://user-images.githubusercontent.com/43714758/62438166-3355ca00-b714-11e9-97c6-1d5cf07f1e48.png)

If you close the screen manually it works, but will keep bringing up the screen every subsequent fight.

**Comment by TryBane** [comment]
Okay, I know what this is pertaining to, but I don't know exactly where to implement the fix. I'll take a look.

**Comment by TryBane** [comment]
Okay, after reviewing the code, I have no clue what might be causing this. The workflow of the script should be behaving like normal. The only thing I changed originally was in the result menu. And the reason skills were being clicked during second run was I skipped right to Support screen instead of Menu, which in turn kept the battle module from resetting. That was fixed with a slight modification, but this behavior shouldn't be occurring from that. I'll have to further inspect the code.

@w-san if you are experiencing this as well, please let me know. And if not, that is important too.

**Comment by Kasdu** [comment]
Would it help you if I record it happening?

**Comment by TryBane** [comment]
It may very well help.

The script has the potential to click a target on every wave, but usually doesn't because Danger and Servant enemies aren't usually on every wave aside from select Event quests. And those should be the only instances that the script tries to click on one. Unless a stray click is occurring somewhere...

**Comment by TryBane** [comment]
If you record it, please do so from the time it accepts the continue option after results screen till it gets back to the next result screen.

**Comment by Kasdu** [comment]
https://youtu.be/sjYal7SSnpE
The script won't do anything until that screen is closed manually. Previously I left it open for a while to see if the script would automatically close it after a certain amount of time, but it never did.

**Comment by TryBane** [comment]
Okay, are those clicks on the bottom right of the screen from you or the script?

**Comment by Kasdu** [comment]
None of clicks on the video are mine, all are done by the script. Those are the clicks that are bringing up the buff and debuff screen.

**Comment by TryBane** [comment]
Hmmm, then that is weird. Do you have the latest version of Ankulua?

**Comment by Kasdu** [comment]
Yeah, I have 8.5.2, and the only thing that I changed on the fgo jp lua was to enable auto refill and auto skill.

**Comment by TryBane** [comment]
Right now the only thing I can think of is redownloading the script or turning the service off and on again to reset it.

**Comment by TryBane** [comment]
I figured it out! I just have to make a small adjustment.

**Comment by TryBane** [comment]
Okay, fix implemented. I only figured this out by doing it myself on my own phone because I didn't understand what was going on.

The issue was that when you initiate the script, it goes into support, then after selecting the support it clicks on start quest and then checks if there is an Event boost item and either declines it or selects one then accepts. And when the continue option is chosen, it goes back and tries doing that again. Your game loads really fast though, meaning it loads in and then tries to do the start quest and decline booster items.

So, I made a new variable to designate that you are continuing or not. And when you are, it doesn't enter the process for start quest, only selecting your support. Give it a test and let me know if there are any errors with a screenshot plz.

**Comment by w-san** [comment]
Ahh im glad the issue was resolved.

**Comment by TryBane** [comment]
Well, he hasn't responded. So either he fell asleep, or it was indeed a good resolution. I am home now, so I'm going to clean it up a bit and then make a Pull Request.

**Comment by w-san** [comment]
Okay.

**Comment by 29988122** [comment]
I can test ofc...XD
So, thanks for your code, TryBane!

<--Still doing graduate school's advisor meeting, feeling good into 4th year.........(sarcastic tone)

**Comment by TryBane** [comment]
@29988122 I have the completed makeover of this bit of code change now in a pull request at #203

**Comment by 29988122** [comment]
Tested with normal case and stamina refilling case, working well!

Thank you for implementing and sorting this out. < 3
