### ISSUE TITLE
Still getting stuck on Victory Material Window

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#225]
I discussed it with TryBane and we thought it might be able to be fixed by changing line 134 back from the edited 35 back to 45.

Unfortunately this solution didn't work and it still occasionally happens every few battles.

For now I'll try changing it to 60 in the hopes a higher number will help more.

But do you guys have any other suggestions in the meantime?

Picture same as last time
https://send-anywhere.com/web/downloads/882P0DAM

**Comment by Rajvir8** [comment]
Switching to 60 fixed it.

Along with restarting to minimize lag.

**Comment by TryBane** [comment]
No problem! I have also committed with a change to 55 (as that's been working for me) for now.

**Comment by Kizuro** [comment]
For me, even after switching it to 60, 55, 45, or even 35 the script sometimes stuck there.

**Comment by TryBane** [comment]
You can always increase it even more. The higher the number, the longer it'll spend clicking next option. The problem is likely a slow device, which can affect the speed at which menus move to the next. This combined with multiple Bond level ups can easily cause you to have issues even at 60 clicks. So, you can increase the clicks to 65, 70, 75, or even higher if you are still having the issue.

**Comment by Kizuro** [comment]
Welp, the joy of having laggy phone. Thanks for the advice

**Comment by TryBane** [comment]
No worries man, sorry about that
