### ISSUE TITLE
Doesn't continue auto-repeating a node, only runs once

### ISSUE THREAD

**Issue by colourspectrum** [29988122/Fate-Grand-Order_Lua#249]
Once it has finished running the complete node. When it's back to the node selection screen, it just stops there.
Have to manually stop and start Ankulua every time. Once it's started again, it normally continues on to select the node, select support, do battle etc. Than again have to restart ankulua.
Don't know what's the issue, it's not like it can't auto-select the node. As when manually started it chooses that on it's own.
Using Ankulua latest trial APK.

PS can the support selection scroll speed be increased, it's bit too slow and I believe it only detects the support after it has finished the scrolling..

Edit:
Just realized, that it actually works fine. However on the node selection screen, it only proceeds after waiting for around 30 seconds, every time. Had used this script on an older phone previously, it didn't have delay between starting again in that one, so didn't notice it here.
Any way to decrease the delay or anything?

**Comment by TryBane** [comment]
I am working on increasing the scroll speed on Support screen already. I have it much faster already in fact, but it is also too fast XD

As for the wait time, that is because it is looking for friend request screen and first node completion screen. You can reduce this by going into the regular.lua file and finding the "wait(xx)" portions within the Result() function (line 137, 176, 185) and commenting them out. Just bare in mind that first completion will not detect the rewards for first completion and will get stuck there.
