### ISSUE TITLE
Pick waver and buff all allies

### ISSUE THREAD

**Issue by MerryNight** [29988122/Fate-Grand-Order_Lua#29]
You can modify the script to autopick a support waver and enable to use the skill buff all allies from chaldea code? Thanks for read. 10/10 script

**Comment by MerryNight** [comment]
Now I realized how to use the master skills. However, I still want to autopick waver.

**Comment by 29988122** [comment]
Sorry, can't really understand what you mean of "autopick waver"

Can you try to explain it?

**Comment by aqer** [comment]
He wants to autopick servant "Waver" when choosing support servant.

**Comment by 29988122** [comment]
Oh....got it, language barrier.
Our cute little Lord El-Melloi II in Zhuge Liang, right?

It definitely can be done, but since I need to figure out how to do it properly, could take a while. 
Lots of exception handling and screenshot has to be done. 
So soon™

In the meantime, you can try contribute some $$$ to Delightworks and Typemoon, and hope to get either Merlin or Waver for yourself : -

**Comment by Jared-Lee** [comment]
如同類似這篇的需求，希望有一個功能可以自動選取加絆禮裝(英靈肖像/ 學妹 午餐 カルデア・ランチタイム)來對應在FREE本減半的時候可以刷低AP的關卡來刷絆。
無論如何，感謝了。

**Comment by 29988122** [comment]
I guess the flow can be executed like:
1. user screenshot and crop servant/Reisou that you wanna choose
2. put it in folder
3. modify config to enable this function
4. script will search the first page of support list for it; if not existed, execute as normal.

**Comment by 29988122** [comment]
@MerryNight @Jared-Lee 

Now it's supported in version 2.0.0. 
Check readme for further info!
