### ISSUE TITLE
Note 10+ Issues, EN server

### ISSUE THREAD

**Issue by observeroftime02** [29988122/Fate-Grand-Order_Lua#333]
Hey,

I've been using the JP version of the script for playing on my JP account without much of an issue on my note 10+, but the EN version of the script won't make it past the support page. When started from the menu, it picks the quest just fine, but then it gets stuck on the support page (doesn't scroll or interact with it in any way). Here's two screenshots from both the JP version and the EN version on my phone.

EN:
![Screenshot_20200204-194323_Fate_GO](https://user-images.githubusercontent.com/43228249/73815110-cc37d180-4799-11ea-8c4c-554aa10fab5b.png)

JP:
![Screenshot_20200204-194310_FateGO](https://user-images.githubusercontent.com/43228249/73815120-d0fc8580-4799-11ea-8f53-23dfe0a62584.png)

I notice that the game area is noticeably different for both, the JP version is offset by about 62 pixels when compared to the EN version. What can I do to get the EN version of the script to work for me? Any ideas?

EN version works fine on an emulator or my old Note 5, but having to switch accounts back and forth is a pain in the ass. I think it might have something to do with the game area, is there someplace where I can tweak the offset?

**Comment by cboldes** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/issues/310

This is what I was directed to when I asked. I guess if you'd like to work together some how we much be able to fix it? I also have a Note 10+

**Comment by observeroftime02** [comment]
I tried setting every which resolution via ADB on my device, and nothing works. 
I've went to settings -> display -> full screen apps - > advanced, turned on the black bar to cover the camera notch, thinking it might help, it didn't. Running the game in full screen or auto also doesn't seem to affect anything.

What I have noticed is that when i rotate the device 180 degrees, it will no longer manage to select the quest, turn it around 180 degrees again, and it selects the quest just fine. But that's as far as it goes. 

I believe this to be a scaling problem, but I am absolutely not sure what to do about it.

**Comment by cboldes** [comment]
Well you've attempted what I've done so far. Have you by chance tried what I linked? You'll notice reply near the end of the thread with some help. I failed on my side maybe I did something wrong.

**Comment by observeroftime02** [comment]
Regrettably, I'm getting nowhere with this. If I could manually specify the game area somehow, that would help I think.

**Comment by cboldes** [comment]
@observeroftime02 Did you ever check what I sent? Cause I'd like to figure it out also, and we can always get a Dev to help out in the end.

**Comment by observeroftime02** [comment]
I'm sorry, what did you send and to where? I've had a look at the thread you linked and the pull requests mentioned in there to deal with the resolution issues, but the solution in the end was "upgrade to android 9", which isn't possible since my note 10 runs on Android 10 already. For now, I have to run on my old note 5, which sucks performance wise.

**Comment by cboldes** [comment]
@observeroftime02 there's a last bit that @potchy replied to me on. With other threads pertaining to this.

**Comment by potchy** [comment]
you can highlight the game area the script is trying to work on by placing the code `gameWithoutBordersAndNotch:highlight()` above this line: https://github.com/29988122/Fate-Grand-Order_Lua/blob/064dda6997678882354655c0d855ba3fbf1966af/modules/scaling.lua#L52

**Comment by cboldes** [comment]
@potchy I will give it a try in a few hours and tell you the results.

**Comment by cboldes** [comment]
@potchy sorry that took longer than I should have.  This is where the game boarder is currently for my screen. 
![Screenshot_20200206-233121_Fate_GO](https://user-images.githubusercontent.com/41028132/74003703-2de27200-4939-11ea-8078-7447a115152e.jpg)

**Comment by kanerex** [comment]
Having the same issue, this is my screenshot of the game border.
This has been working for months, I haven't changed a single thing, not in ankulua, not in the script, not in fate besides the Valentine's day event update.
The script won't interact with anything on the screen. I updated to the newest version of the script and still nothing.

![Screenshot_20200207-191251_Fate_GO](https://user-images.githubusercontent.com/60800933/74074935-5d978580-49de-11ea-8a6a-21332bd1d93e.png)

**Comment by cboldes** [comment]
@kanerex that's odd my script picks the event, why is my boarder different than yours?

**Comment by Enfinit** [comment]
![Screenshot_20200206-225539_Fate_GO](https://user-images.githubusercontent.com/22234216/74077514-4365a380-49ee-11ea-85c6-49302f55c04a.jpg)

Mine is similar but also slightly different from yours @cboldes 

@kanerex did you happen to update your phone by chance? I remember the script working for a time on ankulua but then when I updated to apply a security patch, that's when things started getting weird for me.

**Comment by cboldes** [comment]
@Enfinit I updated mine for a patch recently. Mine looks a bit wider than yours. By chance is your resolution different? Mine is at FHD+ (2280x1080).

**Comment by Enfinit** [comment]
@cboldes Nope, mine is also at FHD+. By chance did you install the Feb 1st update? I haven't installed that yet which could be the difference.

**Comment by cboldes** [comment]
I did install that update, but I haven't had the script work for a month and a half. It worked on my pixel but I bought this Note 10+ back in January so unless there is something different from my note than everyone else's I'm unsure.

**Comment by Enfinit** [comment]
I just trid the update and yeah, its still the same as before. Not sure why ours are different.

**Comment by cboldes** [comment]
I might have found a difference. Do you have display zoom default?

**Comment by cboldes** [comment]
Well shoot I checked the display and it was still way over to the right.

**Comment by Enfinit** [comment]
Yes my zoom is on default. I'm currently trying to set the game area manually but I'm not sure how to get the highlight function to work with it. I'll mess with it more tomorrow when I get home from work.

**Comment by kanerex** [comment]
So, don't know if this will help, but I got mine working.
Here is what I did.
I disabled all of my accessibility permissions.
Powercycled my phone. (Actually turned it off, not hitting restart, and turned it back on).
I booted Ankulua while accessibility was still disabled, and it of course failed the check for root/daemon/accessibility.
I closed Ankulua, then reenabled all of the accessibility permissions.
I powercycled my phone once more, and then tried running the script, and it functioned without any hiccups.

I'm running my phone in immersive mode, with the notification bar set to gesture, and I have Fate set to force fullscreen.

**Comment by cboldes** [comment]
@kanerex I guess when you say accessibility permissions you mean the services? Cause most of accessibility is already disabled.

**Comment by kanerex** [comment]
@cboldes Just the permissions for ankulua. That allow it to click your screen for you.
![Screenshot_20200208-064830_Accessibility](https://user-images.githubusercontent.com/60800933/74084649-1097cb80-4a3f-11ea-8984-c21b9ebf204c.png)

Installed services

![Screenshot_20200208-064825_Settings](https://user-images.githubusercontent.com/60800933/74084651-155c7f80-4a3f-11ea-8b21-f431b2349030.jpg)

Permissions for Ankulua to use accessibility to click screen/do other functions without your input.

**Comment by Enfinit** [comment]
@kanerex Yeah that doesn't do anything for me. Our problem seems to be the scaling. Did you make any modifications to the scaling.lua file at all? Are you using any launchers?

**Comment by kanerex** [comment]
@Enfinit No, the only things I did are what was in my other post from 8ish hours ago (from the time of posting this), like three posts up.

I am using Goodlock, and have Samfix. And systemUItuner installed.

**Comment by cboldes** [comment]
Well sorry for the delay, but that didn't do anything for me.

**Comment by kanerex** [comment]
Well, I'd like to try and trace the source of the issue, so on line 53 add 
gameWithBorders:highlight()
Screenshot it
Then replace that with gameWithoutBorders:highlight()
Screenshot it.
Post both so we can deduce where the problem starts.

**Comment by cboldes** [comment]
gameWithBorders:highlight()

![Screenshot_20200208-105839_Fate_GO](https://user-images.githubusercontent.com/41028132/74089038-7d708d00-4a62-11ea-9144-5820ecd014b1.jpg)

gameWithoutBorders:highlight()

![Screenshot_20200208-110004_Fate_GO](https://user-images.githubusercontent.com/41028132/74089048-95e0a780-4a62-11ea-949e-f5d4a2850c3f.jpg)

gameWithoutBordersAndNotch:highlight()

![Screenshot_20200206-233121_Fate_GO](https://user-images.githubusercontent.com/41028132/74089057-ad1f9500-4a62-11ea-8ae7-e9006662887b.jpg)

**Comment by kanerex** [comment]
Ok so it is completely offset from the very beginning.
Can you try going into settings->display->fullscreen apps and then enable fullscreen for Fate.
It says it may not work properly but it works perfectly fine, itll change the black borders into a static image.

**Comment by cboldes** [comment]
Yeah I've seen it before.

gameWithBorders:highlight()
![Screenshot_20200208-111603_Fate_GO](https://user-images.githubusercontent.com/41028132/74089206-70549d80-4a64-11ea-9560-0eb0a1a657c4.jpg)


gameWithoutBorders:highlight()
![Screenshot_20200208-111938_Fate_GO](https://user-images.githubusercontent.com/41028132/74089244-f40e8a00-4a64-11ea-9a42-961b8a46bc76.jpg)


gameWithoutBordersAndNotch:highlight()

![Screenshot_20200208-112039_Fate_GO](https://user-images.githubusercontent.com/41028132/74089259-143e4900-4a65-11ea-8985-8c8bab0716b9.jpg)


Also unsure if related but I had the border move when I took a Screenshot. I thought it would be worth mentioning it maybe? I thought the border was more static. 

![Screenshot_20200208-111146_Fate_GO](https://user-images.githubusercontent.com/41028132/74089283-418af700-4a65-11ea-9d11-1e762a7c98c1.jpg)

**Comment by Enfinit** [comment]
My images look the same as well.

**Comment by kanerex** [comment]
I'm at work for another two hours, when I get home I'll see if I can't figure up a custom change to the code to account for the pixel area not being covered by the border, and then we can work from there to figure up exactly where we need the formula.

So baseline what needs to be done if anyone wants to give it a go while I'm working.

gameWithBorder needs to have slightly more width as it's not accurately capturing the width of the screen.

Easiest way to accomplish this would be width + x = screen width. With x being the difference between the current incorrect left border edge in order to account for the whole screen.

Then we will have to figure up the difference in border size from the code to your screen, it should be very minimal, and fall within the margin of error, but it's best to see where gameWithoutBorders places then screen so we can be as accurate as possible and make adjustments where needed.

And finally, find the new offset to shift the border by, in order to place it mid screen. 

I'll give it shot after work,

**Comment by cboldes** [comment]
Hopefully one of the others can provide information for this part. I'm currently out of town and do edits on the fly trying to provide information when I can.

**Comment by Enfinit** [comment]
I'll try and help out as much as I can.

**Comment by kanerex** [comment]
So I checked something, I have my phone set to wqhd+ and not fdh+.
I'm not sure if it will make a difference (as it still worked in fhd+ for me 🤷🏼‍♂️) but it's worth a test while I look over the information we have so far.

**Comment by Enfinit** [comment]
That didn't really do too much. Just shifted the border to the left a bit.

**Comment by cboldes** [comment]
@kanerex Checked my settings and I see that I'm actually on WQHD+ I believe I switched that last night. So all screen shots are in WQHD+ and any previous ones I sent a day or so ago would be in FHD+.

**Comment by kanerex** [comment]
Alright, so after doing a bit of looking, I want to try something.
On line 46 of the scaling lua, 

 https://github.com/29988122/Fate-Grand-Order_Lua/blob/064dda6997678882354655c0d855ba3fbf1966af/modules/scaling.lua#L44-L46

Change `autoGameArea(true)` to `autoGameArea(false)`
See if the script runs, if it doesn't check the borders and post the screenshots.

**Comment by Enfinit** [comment]
@kanerex I've tried playing around with the ImmersiveMode and autoGameArea last night but no dice.
![Screenshot_20200208-163345_Fate_GO](https://user-images.githubusercontent.com/22234216/74092389-08687c00-4a91-11ea-8059-5ef5420f2286.jpg)

I was however able to partially get the script to work at one point, but it would just randomly select supports.

**Comment by kanerex** [comment]
For checking the borders, can you do a screenshot of all three?
gameWithoutBordersAndNotch:highlight()
gameWithoutBorders:highlight()
And
gameWithBorders:highlight()
With autoGameArea set to false?

**Comment by kanerex** [comment]
You can actually do all three at once to help save time. 
![Screenshot_20200208-165355_Fate_GO](https://user-images.githubusercontent.com/60800933/74092561-becd6080-4a93-11ea-9af9-2b2c6292701d.png)

**Comment by Enfinit** [comment]
![Screenshot_20200208-165728_Fate_GO](https://user-images.githubusercontent.com/22234216/74092589-34393100-4a94-11ea-9a27-67492f489bc8.jpg)

**Comment by kanerex** [comment]
Thank-you. 
Setting it to false looks like it helps the scaling a bit, but it's not quite there. 

Reading what setting it to false does, actually makes it feel more universal, and honestly I feel like it should be false by default, if you're going to do all the math manually to determine the border and notch size. As is done in this script, because it forces ankulua to set the entire screen as the area until further specified.

Let me check into this new screenshot and see exactly how far off and maybe determine why.

**Comment by cboldes** [comment]
@kanerex I am also pleased to report from two rounds that the script works properly when it's set to false. So that's two confirmations.

**Comment by kanerex** [comment]
@cboldes it's still not exact, and might misclick for certain things.
This can be a temporary work around until I can finish figuring up how to get it exact. 
I can't guarantee that it will work _perfectly_ for all scenarios until then though. 

Thanks for sticking with me on this. It's trial and error on my end because it's not affecting my note 10 for some reasons. 

And, no offence to the dev's of course, everyone who has worked on this script has done wonders, but the lack of comments, and overall "spaghettiness" of the code makes it a bit more difficult to parse. 
Of with reading anyone else's code, without them present (especially on an open source project like this one that's had many hands in the dish) will always come with issues as everyone codes in their own style.

**Comment by cboldes** [comment]
@kanerex I agree with you there and I'm not sure why your Note 10+ is acting different. I know how to code, but I was honestly unsure of where to begin so I give you kudos. For about a month I knew it dealt scaling, but was unsure how and where to approach it in the module.

**Comment by potchy** [comment]
The `highlight` function is actually pretty weird.
Here's how it looks on my phone:

![Screenshot_20200208-192452_Fate_GO](https://user-images.githubusercontent.com/4316326/74092912-918bad00-4aa9-11ea-9f23-9e764477589f.png)

Notice that the highlight was set to a completely different position than the one that was calculated, yet the script works perfectly, because the calculated regions are correct for my phone `(207, 0, 1920, 1080)`.
[I had questioned AnkuLua's author about it before](http://ankulua.boards.net/post/14469/thread), but I'm still not sure `highlight` works.
In fact, if you call `highlight` _after_ `setGameArea`, `Settings:setScriptDimension` and `setCompareDimension`, it will give a completely different result (that also doesn't make any sense):

![Screenshot_20200208-193046_Fate_GO](https://user-images.githubusercontent.com/4316326/74093046-6a35df80-4aab-11ea-8160-d8f42f6db984.png)


---

Anyway, sending `false` as an argument to `autoGameArea` breaks the calculation on my phone:

![Screenshot_20200208-193637_Fate_GO](https://user-images.githubusercontent.com/4316326/74093159-ebda3d00-4aac-11ea-9a36-485eba26c86e.png)


Here's the code for the dialog:
```lua
dialogInit()
local message = "getRealScreenSize(): %ix%i\n"
message = message .. "getAppUsableScreenSize(): %ix%i\n"
message = message .. "gameWithBorders: Region(%i, %i, %i, %i)\n"
message = message .. "gameWithoutBorders: Region(%i, %i, %i, %i)\n"
message = message .. "gameWithoutBordersAndNotch: Region(%i, %i, %i, %i)"
message = message:format(getRealScreenSize():getX(), getRealScreenSize():getY()
					   , getAppUsableScreenSize():getX(), getAppUsableScreenSize():getY()
					   , gameWithBorders:getX(), gameWithBorders:getY(), gameWithBorders:getW(), gameWithBorders:getH()
					   , gameWithoutBorders:getX(), gameWithoutBorders:getY(), gameWithoutBorders:getW(), gameWithoutBorders:getH()
					   , gameWithoutBordersAndNotch:getX(), gameWithoutBordersAndNotch:getY(), gameWithoutBordersAndNotch:getW(), gameWithoutBordersAndNotch:getH())
addTextView(message)
dialogShow("Resolution")
```

---

I think our biggest problem is `getGameArea` itself.
Originally, and before AnkuLua's author included `getGameArea` in the framework, the script only worked for phones without a notch. [Here](https://github.com/29988122/Fate-Grand-Order_Lua/blob/580bb83042ce500612c276df0df7604d746725c0/modules/scaling.lua)'s one of `scaling.lua` first revisions. You can see that most of the formulas are still exactly like they are today. The only noticeable difference is that we used to call `getRealScreenSize` instead of `getGameArea`. Unfortunately, it's the only resource we have to get the notch size. I'm not confident it works for every phone and notch size there is. If it did, we wouldn't have so many threads open about the same issue. I'm afraid the most sensible solution is to include a setting so that users can manually set the offsets that work for them.

---

> And, no offence to the dev's of course, everyone who has worked on this script has done wonders, but the lack of comments, and overall "spaghettiness" of the code makes it a bit more difficult to parse.

While I agree that the code base isn't in an exact perfect state, the scaling part, specifically, is only 63 lines long and there's also a [diagram](https://raw.githubusercontent.com/29988122/Fate-Grand-Order_Lua/master/docs/scaling.png) available to help fellow readers, so it shouldn't pose much of a problem, I think.

There were some people actively working in the code, but I believe they got new priorities. Take me for, example. I now have a very time consuming job, so I prefer to devote the little free time I have to other stuff. After all, the script got to a state that it works good enough for my personal use, so you could say my laziness and selfishness played a part in it as well.

I'm not trying to boast or anything, just trying to explain why you don't see much new commits being made nowadays, but I'm willing to help newcomers understand the code and its history.

**Comment by kanerex** [comment]
That diagram is actually really helpful. 

What I think is going on here, and from my understanding from reading the Ankulua dev's posts over on their forum, is that when `getGameArea` was originally created phones with the resolution, and dimensions of the likes of the Note 10+, probably weren't accounted for.

It would explain why when `autoGameArea` is set to false it is able to see the full screen. 
Like when you compare 
This screenshot
![74089206-70549d80-4a64-11ea-9560-0eb0a1a657c4 (1)](https://user-images.githubusercontent.com/60800933/74093969-b121d600-4aa7-11ea-8006-b45a07915639.jpg)

Which is of `gameWithBorders` with `autoGameArea` set to true.

And compare it to 
![74092389-08687c00-4a91-11ea-8059-5ef5420f2286](https://user-images.githubusercontent.com/60800933/74093986-efb79080-4aa7-11ea-9990-7061e1571c78.jpg)

This screenshot, where the highlighted region (although we don't have the exact region that is being used which I admit would be more helpful, and I'll take that into consideration upon further troubleshooting) for `gameWithBorders` actually fills the whole screen, after setting `autoGameArea` to false, as would be expected. Seeing as `gameWithBorders` is before the borders or notch are removed.

With this in mind, I can only conclude that `autoGameArea` has some kind of built in hard limit in region size that it can detect, as odd as that might be.
Although seeing the Note 10+'s true resolution of 3040x1440, a 38:18 aspect ratio, it's safe to make the assumption that this sort of screen was never actually considered when making the framework.

All that aside though, thank-you @potchy for the information. I'm going to keep working on this in my free time and see if I can't come up with a solution. although I do feel that, as you said, a setting that allowed you to toggle between a manual offset input, or the default automated one would be the _best_ solution, it might not be the most end user friendly... though I don't know if that really matters to he honest.

**Comment by cboldes** [comment]
@potchy Thank you for the information! Any help is wonderful and I completely understand thank you for providing any advice.

**Comment by TryBane** [comment]
As potchy stated, a lot of us have not been too active in making commits to make changes. For myself, it is simply a matter of time and inspiration. A lot of my own time is taken up by work, in which I work a lot of overtime (to pay for my gacha game) and the rest by other recreational activities (to keep myself sane). But when I get inspiration, I usually find it enjoyable enough to program and use that as my method of keeping sane.

Anyways, the main method I've found of solving this (which isn't a perfect solution) is providing a manual offset based on your own device. The plus side to this, it should work immediately. The negative side is it requires your phone to be in a specific orientation for the script to work. For instance, if you provide the offset for when the notch is on the left hand side, the notch always has to be on the left side when you run the script for it to work.

**Comment by cboldes** [comment]
@TryBane Thank you for the information. I've been looking for it on my end. So far the method of turning it to false has mitigated the issue, while it doesn't truly fix it. This does give insight on what I'm looking for and I understand we all have lives just bits of advice is always helpful. ☺️

**Comment by TryBane** [comment]
To clarify, line 41 of scaling.lua is the return function that takes in the notchoffset. All you have to do is replace notchoffset with a literal value (a number) and it will work, assuming the offset is correct. To figure out this offset, go ahead and take a screenshot of your phone and put it in an image editor (there is an online one for free you can use on your phone even). Scale it to 720 (or 1440 if the editor allows for it) and create a crop area. Drag said crop area to the left side and resize it till it fits the bar on the side. If you're on JP, this will be fairly easy as JP has blue background for the borders and black for the notch area. You can use the x value of that for the offset. If you are not using JP, then you'll have to compare one side with the other, and subtract the size for the difference.

Once you have that, you'll have to ensure it is based on 1440p size. Meaning if you had to scale down to 720p, you'll have to double the x value. If it was 1440p, then the value is fine as it is. This is the value you can place in the function I mentioned above. Line 41 of scaling.lua. if it doesn't work the first time, flip the screen around and try it again. If it still doesn't work, come back and I'll try to figure out why. Please bring screenshots.

**Comment by TryBane** [comment]
@cboldes your reply came faster than I could finish typing (on my phone and at work) but feel free to give what I mentioned above a try and see if it works. Again, if it doesn't, please bring screenshots of your device and I'll try to help you.

**Comment by cboldes** [comment]
@TryBane Can do! I'll probably be at work the next time I reply to this... Haha

**Comment by kanerex** [comment]
I think I'm going to make an elegant solution that uses a radio button toggle between the auto detection size, and a manual input prompt on script start.
I won't be free till tomorrow afternoon have had a pretty hectic work week this week. Lol

**Comment by kanerex** [comment]
I've been working on, as time permits, a radial button toggle that let's you swap between inputting your own values in dialog boxes, or the automated version.
I might include something that detects the side The notch is on, so it can be a universal fix, in a v2 after I get this working.
Been a hectic work week though, I won't be able to work on it again till tomorrow afternoon eastern time.

**Comment by TryBane** [comment]
Hey man, if you get it working then defs do a pull request for it if you're willing. We'd gladly implement it into the regular version

**Comment by observeroftime02** [comment]
If you need someone to run some tests with a note 10+, i'd be more than happy to help.

**Comment by reconman** [comment]
Can you try this? https://github.com/29988122/Fate-Grand-Order_Lua/issues/310#issuecomment-586916790

**Comment by reconman** [comment]
Closing since there's no reaction.
