### ISSUE TITLE
Script runs but does not function

### ISSUE THREAD

**Issue by ValBlades** [29988122/Fate-Grand-Order_Lua#378]
Essentially, the issue is as follows: I start the script. but it does not perform any touches/drags on my screen. It does not select a support. It does not perform autoskill actions, It just idles. No error messages appear.

Phone Model: Samsung Galaxy A10e
Android Version: 9 (non-rooted; Accessibility is enabled)
Ankulua Version: 8.7.0 trial
Party Comp: Saber Lily. Sieg, Caster Gilgamesh, Waver, Kojiro, Chacha
Node being used on: Hatamoto
Screen Resolution; 720x1560 pixels
FGO_EN
Using latest release version of script? Yes

Battle is supposed to go as follows:
T1:
> Gilgamesh Caster uses S3, S2, S1
> Sieg uses S1
> Saber Lily uses S3
> Switch Gilgamesh Caster for Waver with MC
> Waver uses S3 and S2
> Sieg NPs

T2:
> Waver uses S1, targeting Sieg
>Sieg uses S3 and S2
>Sieg NPs
 
T3:
>Activate Master Skill 1
>Saber Lily uses S2 and S1
>Saber Lily NPs

**Comment by reconman** [comment]
See https://29988122.github.io/Fate-Grand-Order_Lua/#/troubleshooting?id=the-script-clicks-in-the-wrong-locations-or-does-nothing-at-all

You need to set autoGameArea to false.

Make sure that you're running the app in Samsung's fullscreen mode (with blue bars on the sides), otherwise FGO is not in the middle of the screen.

After that, support mode `preferred` won't work because Accessibility does not support `manualTouch`, which is used there.

You will need to replace it with `dragDrop` from here https://ankulua.boards.net/thread/6/objects-methods-introduction-sikuli-compatible

Since you're only getting started, I can also recommend the totally free port of fgolua here: https://github.com/MathewSachin/Fate-Grand-Automata

Just make sure to read https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/SAMSUNG.md

**Comment by ValBlades** [comment]
Thank you for the quick reply! Changing set AutoGameArea to false and setting FGO to fullscreen mode did rectify the issue. I am unsure of how to change manualTouch to dragDrop (unsure of which module to edit and what line).

The script worked. The only issue is that it did not execute my turn 2 commands and went straight for face cards (at which point I stopped it). 
![Screenshot_20200513-190254_ES_File_Explorer 1](https://user-images.githubusercontent.com/61525943/81878079-89ca2180-954c-11ea-882e-42ac525c2bdd.jpg)

**Comment by reconman** [comment]
Sorry for the late answer, you are missing `#` in your Hatamoto Skill_Command.
