### ISSUE TITLE
Accesibility mode does not support manualTouch

### ISSUE THREAD

**Issue by Cerz0** [29988122/Fate-Grand-Order_Lua#390]
So a few days ago got this error:

![image](https://user-images.githubusercontent.com/62533167/84691029-bd310f00-af43-11ea-908a-0341d625686d.png)

When trying to reinstall the daemon i get this:
![image](https://user-images.githubusercontent.com/62533167/84690942-97a40580-af43-11ea-82ac-5584b5de77bf.png)

Is not the first time, sometimes it ramdomly goes back to working fine, not happening now though.

**Comment by MathewSachin** [comment]
In AnkuLua settings, there is a `Touch By` setting. Maybe that got set to `Accessibility`.

Actually, `Accessibility` works fine on Android 7 otherwise on my phone (i.e. without daemon).
You just have to replace `manualTouch` with `swipe`.
See my comment on another issue for more info: https://github.com/29988122/Fate-Grand-Order_Lua/issues/370#issuecomment-629608887

**Comment by Cerz0** [comment]
liket this?
![image](https://user-images.githubusercontent.com/62533167/84695048-81e60e80-af4a-11ea-832f-1a4f9afa211b.png)

**Comment by Cerz0** [comment]
Ok, did that, seems to work fine, the swipes are quite fast but hasn't caused any problems yet

**Comment by MathewSachin** [comment]
Take a look at the linked comment. I've explained how to change the `Game.SupportSwipeEndClick` such that the script won't scroll too much. You can further adjust it to your need.
