### ISSUE TITLE
Unable to use boost item when repeating a quest

### ISSUE THREAD

**Issue by Wescj** [29988122/Fate-Grand-Order_Lua#404]
When you press the repeat button the game does not automatically pick another boost item. Is it possible to not press the repeat button and instead return to the main menu? Or just do the quest with one repetition.

**Comment by reconman** [comment]
For me personally this seems like a situation DW didn't foresee. Since the boost item screen appears on the Party Selection screen, and that screen doesn't appear when you repeat the quest, you can never use boost items in repeated runs.

Clicking Close doesn't throw you back to the screen where the last quest is in the top right.

It would take a miracle to be able to support using boost items for repeats:

1. Someone who is located in the official NA regions reports the problem to the FGO US support
2. DW can somehow find a solution where you can select the boost item during repeats, updates the server, and probably also updates the APK in the Play Store
3. We look at the UI changes made in 2. and implement this feature.
