### ISSUE TITLE
Select favorite servant

### ISSUE THREAD

**Issue by matp07289** [29988122/Fate-Grand-Order_Lua#58]
If friends servant select,I want select  "Gilgames" but,not display friends, so I want refresh and use image file select "Gilgames"

**Comment by 29988122** [comment]
Your concern is mentioned here:
https://github.com/29988122/Fate-Grand-Order_Lua/pull/42

We may implement it, sooner or later, before that please be patient : D

**Comment by matp07289** [comment]
I see.  and Ankulua limited time 30m, so stop battle time, I want  another
macro app....

2018-08-10 15:18 GMT+09:00 Jerry Ho <notifications@github.com>:

**Comment by 29988122** [comment]
https://www.google.com.tw/search?source=hp&ei=1DltW-K8O8iC8gW5nbDoAw&q=robomon&oq=robomon&gs_l=psy-ab.3..35i39k1j0j0i10k1j0l7.208.208.0.438.2.1.0.0.0.0.124.124.0j1.1.0..1..0...1..64.psy-ab..1.1.123.0...0.Re1OJmT_1fk

You can try this, it also has FGO script. You may need Chrome to translate the page, it's in Chinese.

I don't earn $$ from Ankulua or Robotmon, so I respect their decision about $$.
There's literally ZERO other macro app good enough, so that's why I chose Ankulua despite it's $$.
Besides, It's harder to make Ankulua/Robotmon than this FGO script. They should earn $$ for hard work.
Difficulty Ankulua=Robotmon >>>>>>>>> FGO_LUA_script.

**Comment by matp07289** [comment]
HELLO, autoskill list clash,,,

2018年8月10日(金) 16:11 Jerry Ho <notifications@github.com>:

**Comment by 29988122** [comment]
Are you using this version?
https://github.com/29988122/Fate-Grand-Order_Lua/releases/tag/1.9.3
Can you please take a screenshot of error?


Take error picture, so I can help you

**Comment by matp07289** [comment]
[image: WS000000.JPG]

2018年8月13日(月) 14:50 Jerry Ho <notifications@github.com>:

**Comment by matp07289** [comment]
![ws000000](https://user-images.githubusercontent.com/40632392/44015723-153f3e2c-9f0d-11e8-92ce-f3bd9f177535.JPG)

**Comment by 29988122** [comment]
変だな…これはankuluaの問題で、スクリプトの問題じゃないはず。

1.古いバージョンのスクリプトで試してください（1.9.0とそれ以前）、問題はまだあるかどうか教えてください
2.レポートボタンを押して、エラーの内容をなんとか（複数のスクリーンショットとか）こちらに貼ってください

こちらはいま水着イベントを周回中（同人誌修羅場長いw）、
しかしこちらのマシンでは問題は起こらない以上修復しようがない

まずあなたのマシンの問題点を判明し、修復するつもりです

**Comment by matp07289** [comment]
1  リストをoffにするとエラーは起きません　19.3  旧verはまだ
2　レポートを押してもエラー内容は出ません
3  nox app player 
4  ３番め　　g h i のスキルが機能しません

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/commit/b50ccf7b83cb5c7de6a62cce83aa70f9ad09fd4d

これをダウンロードし、NOXに入れてください。
バグは多分治る…かも。

**Comment by matp07289** [comment]
ありがとう！
サポートサーヴァントを選択するときに　UWSC　を使って好きなサーヴァントをスクリーンショットを使って選ぶ方法があるのですが、書き換えることはできますか

https://ja.wikipedia.org/wiki/UWSC

**Comment by 29988122** [comment]
今の段階では無理ですが、私よりすごい人達は頑張っています。
https://github.com/29988122/Fate-Grand-Order_Lua/pull/42
ここで議論しています。

一見簡単な機能かもしれませんが、考えなければならないことは沢山あります。
私もこの機能が欲しいので（笑）、温かい目で見守りましょう！
