### ISSUE TITLE
NPs not being fired automatically anymore

### ISSUE THREAD

**Issue by potchy** [29988122/Fate-Grand-Order_Lua#62]
I've noticed that, in the latest release, Noble Phantasms are not being fired automatically in the last stage (e.g. 2/2 or 3/3).

I just want to confirm if this change was intended or if it is a bug. 
`

    if TargetChoosen == 1 and decodeSkill_NPCasting == 0 then

        --ultcard()

    end
`

**Comment by 29988122** [comment]
Should've separate testing environment and working environment..

Was going to handle this exception:
e.g., "danger", "servant" enemy appeared in battle 2/3, and Autoskill == 1.
If Autoskill did not wipe enemy out, ult() will take over and cast NP. It sometimes messed up Autoskill plan.

Was going to tweak Autoskill(), thus ultcard() will not mess up before every command of Autoskill has been executed.

The modification's not done yet, so yeah comment out that line was a mistake.

**Comment by 29988122** [comment]
Both option works in different scenario I guess. 

Some ppl use Autoskill for Artcard team, so they would need the auto NP behavior; meanwhile player like me depends on Merlin and Kailedoscope for their autoskill, so it can't be messed by the auto NP behavior.

BTW, since I did not not fully understand executeskill() and decodesill() yet...you can implement it for me, or wait for me until some other day xD

**Comment by ryuga93** [comment]
How about adding a character to the command list? When autoskill encounters the character, it will toggle a flag which control np firing, thus user is able to control precisely the auto np

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/commit/8a2bf6debfb7fa3dda81a3d4ede8ab3a414c5ed7
