### ISSUE TITLE
event(Jp)

### ISSUE THREAD

**Issue by saiyansoul** [29988122/Fate-Grand-Order_Lua#8]
For nerofest event,can i just use the event lua or i have to wait for the lua that is special for the event?

**Comment by 29988122** [comment]
Use the latest version that released few hours ago, and yes, execute the regular one.

Rule of thumb on how to choose: 
If you need to do extra click / extra option(like racing, or CCC event), wait for the event.lua. 
Otherwise, regular one should be OK.

You can always try regular one to see if it worked properly.

**Comment by saiyansoul** [comment]
Well thanks! I thought it can't be use for nero.

Alright, I'll do it after clearing challenge quest xD


Thank you
