### ISSUE TITLE
Runtime error occured while selecting preferred support on cn apk 1.36.0

### ISSUE THREAD

**Issue by Zilay** [29988122/Fate-Grand-Order_Lua#87]
This error definitely appear when i use Memu Emulator & the latest version of this script.
It seems like the script unable to identify some block on screen. It will run normally by set ‘Support_PreferredServants’  to be manual or first. I have replaced the 'menu.jpg' & image in 'Support_PreferredCEs' but nothing goes work.
![pgl1o 3mx d ye ok_68yng](https://user-images.githubusercontent.com/37580817/47614654-2d282280-dade-11e8-90bd-250e4d685744.png)
![screenshot_2018-10-28-16-50-56](https://user-images.githubusercontent.com/37580817/47614668-492bc400-dade-11e8-9f5f-21a45e4e452d.png)
![screenshot_2018-10-28-16-51-36](https://user-images.githubusercontent.com/37580817/47614669-49c45a80-dade-11e8-89e7-42c9d9e88651.png)

**Comment by potchy** [comment]
The error message is saying that, for some reason, the script could not find the snapshot() function in AnkuLua. Since we have no control over it, you just need to make sure you're using one of AnkuLua's latest releases. Any of these should work:
- [7.6.0-trial](https://play.google.com/store/apps/details?id=com.appautomatic.ankulua.trial&hl=pt_BR)
- [7.5.3-pro2](https://www.dropbox.com/s/8ld09qvc8p5vlcz/AnkuLuaPro2.v7.5.3.apk?dl=1) (I'm using this one)
- [8.0.0-pro2](https://www.dropbox.com/s/t7wxym8dfp0crqf/AnkuLuaPro2.v7.6.0.apk?dl=1)

**Comment by Zilay** [comment]
> The error message is saying that, for some reason, the script could not find the snapshot() function in AnkuLua. Since we have no control over it, you just need to make sure you're using one of AnkuLua's latest releases. Any of these should work:
> 
> * [7.6.0-trial](https://play.google.com/store/apps/details?id=com.appautomatic.ankulua.trial&hl=pt_BR)
> * [7.5.3-pro2](https://www.dropbox.com/s/8ld09qvc8p5vlcz/AnkuLuaPro2.v7.5.3.apk?dl=1) (I'm using this one)
> * [8.0.0-pro2](https://www.dropbox.com/s/t7wxym8dfp0crqf/AnkuLuaPro2.v7.6.0.apk?dl=1)
> 
> By the way, in CN you can repeat the challenge quests in Nerofest? 😮

OH, it works after i updated the Ankulua to 7.6.0 trail! Thanks a lot!

I downloaded the Ankulua apk form https://apps.evozi.com/apk-downloader 3 days ago bacause the google play app on emulator was stuck in ‘download pending’. They said that they downloaded  newest apk files from the Google Play directly, but they were lying, i have downloaded a 7.0.0 trail rather than 7.6.0 trail.

In CN, the challenge quests is actually repeatable but you won't get any rewards twice.
